### ISSUE TITLE
I am new to HFO and I would like to try to run your code, but an error is reported

### ISSUE THREAD

**Issue by LuciferDarkStar** [arhik/DDPG_HFO#3]
I'm sorry to bother you, I'm an undergraduate student and I'm recently interested in HFO. I tried to run your code, but an error was reported and I don't know how to fix it. The error is as follows：
******************************************************************
 librcsc 4.1.0
 Copyright 2000 - 2007. Hidehisa Akiyama.
 Copyright 2007 - 2011. Hidehisa Akiyama and Hiroki Shimora
 All rights reserved.
******************************************************************
base_left: init ok.  unum: 11 side: l
base_left 11:  KickTable created.
base_left 11: [0, 1]  prepare see synch
base_left 11: [0, 4]  see synch.
Now we load the weight
Cannot find the weight
Soccer Experiment Start.
Episode : 0 Replay Buffer 0
Traceback (most recent call last):
  File "ddpg.py", line 304, in <module>
    playGame(train_indicator=1)
  File "ddpg.py", line 172, in playGame
    a_t_original = actor.model.predict(s_t.reshape(1, s_t.shape[0]))
  File "/home/vmware/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1254, in predict
    check_batch_axis=False)
  File "/home/vmware/.local/lib/python2.7/site-packages/keras/engine/training.py", line 124, in standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected input_1 to have shape (None, 58) but got array with shape (1, 86)

**Comment by LuciferDarkStar** [comment]
I would be very grateful if you could answer for me as soon as possible

**Comment by arhik** [comment]
Sorry. Hope you managed to work it out. I couldn't reply because of personal reasons.
